services:
  frontend:
    build:
      context: ../art-of-tennis
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
    volumes:
      - ../:/app
  backend:
    build:
      context: ../../backend/tennis
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=db_user
      - DATABASE_PASSWORD=db_password
      - DATABASE_NAME=tennis
      - DATABASE_PORT=5432
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=3000
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:alpine3.19
    environment:
      POSTGRES_DB: tennis
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - art_of_tennis_postgres_front:/var/lib/postgresql/data
volumes:
  art_of_tennis_postgres_front:
