name: Build and Push Docker Images

on:
  pull_request:
    branches:
      - master

jobs:
  get-acr-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        working-directory: infrastructure
        run: |
          terraform init -backend-config='storage_account_name=${{ secrets.TF_STORAGE_ACCOUNT }}' \
                          -backend-config='container_name=${{ secrets.TF_CONTAINER_NAME }}' \
                          -backend-config='key=${{ secrets.TF_STATE_KEY }}' \
                          -backend-config='resource_group_name=${{ secrets.TF_RESOURCE_GROUP }}'
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Get ACR name from Terraform output
        id: get-acr-name
        working-directory: infrastructure
        run: |
          ACR_NAME=$(terraform output -raw name)
          echo "ACR_NAME=${ACR_NAME}" >> $GITHUB_ENV

  build-and-push:
    runs-on: ubuntu-latest
    needs: get-acr-name

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push Docker images
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF_NAME | sed 's/\//-/g')
          for service in service1 service2 service3; do
            docker build -t ${{ env.ACR_NAME }}.azurecr.io/$service:${BRANCH_NAME} -f $service/Dockerfile .
            docker push ${{ env.ACR_NAME }}.azurecr.io/$service:${BRANCH_NAME}
          done
