name: Build and Push Docker Images

on:
  pull_request:
    branches:
      - master

env:
  config_env: "none"

jobs:
  set-env-branch:
    runs-on: ubuntu-latest
    outputs:
      config-file: ${{ steps.set-output-defaults.outputs.config-file }}
    steps:
      - id: set-prod-branch
        name: Set Prod Branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "config_env=config-infra-prod.yml" >> $GITHUB_ENV
      - id: set-dev-branch
        name: Set Dev Branch
        if: ${{ github.ref != 'refs/heads/main' }}
        run: echo "config_env=config-infra-dev.yml" >> $GITHUB_ENV
      - id: set-output-defaults
        name: Set Output Defaults
        run: echo "config-file=$config_env" >> $GITHUB_OUTPUT

  get-config:
    needs: set-env-branch
    uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
    with:
      file_name: ${{ needs.set-env-branch.outputs.config-file }}

  get-acr-name:
    needs: get-config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          terraform -chdir=${{ needs.get-config.outputs.terraform_workingdir }} init \
            -backend-config="storage_account_name=${{ needs.get-config.outputs.terraform_st_storage_account }}" \
            -backend-config="container_name=${{ needs.get-config.outputs.terraform_st_container_name }}" \
            -backend-config="key=${{ needs.get-config.outputs.terraform_st_key }}" \
            -backend-config="resource_group_name=${{ needs.get-config.outputs.terraform_st_resource_group }}"
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Terraform Output
        run: terraform -chdir=${{ needs.get-config.outputs.terraform_workingdir }} output -json > output.json
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Extract ACR Name
        run: |
          ACR_NAME=$(jq -r .name.value output.json)
          echo "ACR_NAME=${ACR_NAME}" >> $GITHUB_ENV

  build-and-push:
    needs: get-acr-name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build and Push Docker Images
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF_NAME | sed 's/\//-/g')
          for service in service1 service2 service3; do
            docker build -t ${{ env.ACR_NAME }}.azurecr.io/$service:${BRANCH_NAME} -f $service/Dockerfile .
            docker push ${{ env.ACR_NAME }}.azurecr.io/$service:${BRANCH_NAME}
          done
