name: Build and Push Docker Images

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      # ACR_NAME: ${{ secrets.ACR_NAME }}
      # TODO: read ACR_NAME from config-infra or from
      # the output of the terraform apply
      ACR_NAME: craot50002dev 
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV

      - name: Build and push backend image
        run: |
          az acr build --registry ${{ env.ACR_NAME }} \
          --image backend-${{ env.BRANCH_NAME }} \
          --target prod backend/tennis/

      - name: Build and push frontend prod image
        run: |
          az acr build --registry ${{ env.ACR_NAME }} \
          --image frontend-${{ env.BRANCH_NAME }} \
          --target prod frontend/art-of-tennis/

      - name: Build and push celery prod image
        run: |
          az acr build --registry ${{ env.ACR_NAME }} \
          --image celery-${{ env.BRANCH_NAME }} \
          --target prod backend/tennis/
